services:
  db:
    build: ./docker/db
    image: todo-mysql:8
    container_name: todo-mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-todo_db}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: todo-app:latest
    container_name: todo-app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ:-Asia/Tokyo}
    expose:
      - "8080"
    restart: unless-stopped

  web:
    build: ./docker/web
    image: todo-web:latest
    container_name: todo-web
    depends_on:
      - app
    ports:
      - "80:80"
    restart: unless-stopped 