apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
    app.kubernetes.io/name: todo-app
    app.kubernetes.io/part-of: todo
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
    - name: http
      port: 8080
      targetPort: 8080 