apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
    app.kubernetes.io/name: todo-web
    app.kubernetes.io/part-of: todo
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: 80 