apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: todo
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "pass"
  DB_PASSWORD: "pass" 