namespace: todo
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: app
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: web
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
images:
  - name: ghcr.io/yamayui1107/todo-app
    newTag: latest
  - name: ghcr.io/yamayui1107/todo-web
    newTag: latest

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: app-props
    behavior: replace
    files:
      - application.properties=./application-dev.properties 