namespace: todo
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: app
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: web
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
images:
  - name: your-registry/todo-app
    newName: ghcr.io/yamayui1107/todo-app
    newTag: latest
  - name: your-registry/todo-web
    newName: ghcr.io/yamayui1107/todo-web
    newTag: latest
secretGenerator:
  - name: db-secret
    envs:
      - secret.env
generatorOptions:
  disableNameSuffixHash: true 