namespace: todo
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: app
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: web
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
images:
  - name: ghcr.io/yamayui1107/todo-app
    newName: ghcr.io/yamayui1107/todo-app
    newTag: "sha-ad4983a"
  - name: ghcr.io/yamayui1107/todo-web
    newName: ghcr.io/yamayui1107/todo-web
    newTag: "sha-9b58bad"
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: app-props
    behavior: replace
    files:
      - application.properties=./application-dev.properties
