namespace: todo-dev
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: app
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: web
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Namespace
      name: todo
    patch: |
      - op: replace
        path: /metadata/name
        value: todo-dev
  - target:
      kind: Ingress
      name: web
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: dev.todo.example.com
images:
  - name: ghcr.io/yamayui1107/todo-app
    newName: ghcr.io/yamayui1107/todo-app
    newTag: "sha-a379a31"
  - name: ghcr.io/yamayui1107/todo-web
    newName: ghcr.io/yamayui1107/todo-web
    newTag: "sha-a379a31"

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: app-props
    behavior: replace
    files:
      - application.properties=./application-dev.properties